# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Swish": "00_core.ipynb",
         "CLOOBEmbedding": "00_core.ipynb",
         "ZEmbedding": "00_core.ipynb",
         "TimeEmbedding": "00_core.ipynb",
         "ResidualBlock": "00_core.ipynb",
         "AttentionBlock": "00_core.ipynb",
         "DownBlock": "00_core.ipynb",
         "UpBlock": "00_core.ipynb",
         "MiddleBlock": "00_core.ipynb",
         "Upsample": "00_core.ipynb",
         "Downsample": "00_core.ipynb",
         "UNet": "00_core.ipynb",
         "DISC": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://johnowhitaker.github.io/cclddg/"

git_url = "https://github.com/johnowhitaker/cclddg/tree/master/"

def custom_doc_links(name): return None
